- id: enable_zigbee_join
  alias: Enable Zigbee joining
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- id: rocky_theme
  alias: Play Rocky Theme when cleaning done
  trigger:
    platform: template
    value_template: '{{ is_state(''vacuum.roborock_vacuum_s5'',''returning'') }}'
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.spotify
      source: Anders's Echo Plus
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify
      media_content_type: music
      media_content_id: spotify:track:6C2PfemHQul77DVpnvuAIs
  - service: media_player.select_source
    data:
      entity_id: media_player.spotify
      source: Anders's Echo Plus
- id: plant_light_on
  alias: Turn on lights
  trigger:
  - platform: time
    at: 06:30
    id: weekday_morning
  - platform: time
    at: 06:45
    id: weekday_morning_bedroom
  - platform: time
    at: 08:00
    id: weekend_morning
  - platform: time
    at: '15:00'
    id: weekend_on
  - platform: time
    at: '16:00'
    id: weekday_afternoon
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: weekday_morning
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: light.turn_on
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
    - conditions:
      - condition: trigger
        id: weekday_morning_bedroom
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.bedroom_plug
        data: {}
    - conditions:
      - condition: trigger
        id: weekend_morning
      - condition: time
        weekday:
          - sat
          - sun
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: light.turn_on
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
    - conditions:
      - condition: trigger
        id: weekday_afternoon
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: light.turn_on
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
    - conditions:
      - condition: trigger
        id: weekend_on
      - condition: time
        weekday:
        - sat
        - sun
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: light.turn_on
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
      - service: switch.turn_on
        target:
          entity_id: switch.bedroom_plug
- id: plant_light_off
  alias: Turn off lights
  trigger:
  - platform: time
    at: 07:45
    id: weekday_morning_bedroom
  - platform: time
    at: 08:00
    id: weekday_morning
  - platform: time
    at: '10:00'
    id: weekend_off
  - platform: time
    at: '22:00'
    id: weekday_afternoon
  - platform: time
    at: '23:00'
    id: weekday_afternoon_bedroom
  - platform: time
    at: '23:59'
    id: weekend_afternoon
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: weekday_morning
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: light.turn_off
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
    - conditions:
      - condition: trigger
        id: weekday_afternoon
      - condition: time
        weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: light.turn_off
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
    - conditions:
      - condition: trigger
        id: weekend_afternoon
      - condition: time
        weekday:
        - fri
        - sat
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.stair_star_plug
        data: {}
      - service: switch.turn_off
        target:
          entity_id: switch.bedroom_plug
        data: {}
      - service: light.turn_off
        target:
          entity_id:
          - light.star_stair
          - light.star_salong_2
          - light.star_salong_1
          - light.star_bar
        data: {}
    - conditions:
      - condition: trigger
        id: weekday_afternoon_bedroom
      - condition: time
        weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.bedroom_plug
        data: {}
- id: christmas_tree_on_workday
  alias: Turn on christmas tree at specific times
  trigger:
  - platform: time
    at:
    - 06:30
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.christmas_tree_plug
- id: christmas_tree_off_workday
  alias: Turn off christmas tree at specific times
  trigger:
  - platform: time
    at:
    - '22:00'
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.christmas_tree_plug
