sensor:
  - platform: mqtt
    name: Dart Plug
    state_topic: "zigbee2mqtt/dart_plug"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/dart_plug/set"
