button_card_templates: !include button_templates.yaml

title: My awesome home
views:
  - title: Hem
    type: custom:horizontal-layout
    layout:
      max_cols: 3
    cards:
      - type: custom:hui-element
        card_type: vertical-stack
        cards:
          - type: entities
            entities:
              - type: custom:slider-entity-row
                entity: light.dart_wall_1
                toggle: true
                hide_when_off: true
              - type: custom:slider-entity-row                
                entity: light.dart_wall_2
                toggle: true
                hide_when_off: true
              - type: custom:hui-element
                card_type: horizontal-stack
                cards:
                  - type: custom:button-card
                    entity: group.pub
                    tap_action:
                      action: toggle
                    name: All
                  - type: custom:button-card
                    entity: switch.dart_plug
                    tap_action:
                      action: toggle
                    name: Dart plug
                  - type: custom:button-card
                    entity: switch.plug_1
                    tap_action:
                      action: toggle
                    name: Pub light
      - type: "custom:light-entity-card"
        entity: light.wled
      - type: picture-glance
        entities:
        - entity: camera.camera
        camera_image: camera.camera
        camera_type: live
      - type: custom:xiaomi-vacuum-map-card
        entity: vacuum.roborock_vacuum_s5
        map_source:
          camera: camera.xiaomi_cloud_map_extractor
        calibration_source:
          camera: true
        map_modes:
          - template: vacuum_clean_zone
          - template: vacuum_clean_zone_predefined
            predefined_selections:
              - zones: [[ 32800, 24767, 38236, 30131 ]]
                label:
                  text: "Bedroom"
                  x: 35932
                  y: 30339
                  offset_y: 35
                icon:
                  name: "mdi:bed"
                  x: 35932
                  y: 26339
      - type: glance
        entities:
        - entity: group.switches_lights
          tap_action:
            action: toggle
          name: Alla
        - entity: switch.christmas_tree_plug
          tap_action:
            action: toggle
          name: Julgran
        - entity: switch.stair_star_plug
          tap_action:
            action: toggle
          name: Trappstjärna
        - entity: switch.dart_plug
          tap_action:
            action: toggle
          name: Dart
        - entity: switch.plug_1
          tap_action:
            action: toggle
          name: Extra Plug
  - title: System
    cards:
    - type: entities
      title: Zigbee
      entities:
      - entity: input_boolean.zigbee_permit_join
      - entity: timer.zigbee_permit_join
      - entity: sensor.bridge_state
      show_header_toggle: false
  - title: Maintenance
    panel: true
    cards:
    - type: picture-glance
      entities:
      - entity: camera.camera
      camera_image: camera.camera
      camera_type: live

